php:
  risky: false
  version: 7.3
  preset: recommended
  tab-width: 4
  use-tabs: false
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "nova"
      - "nova-components"
      - "storage"
      - "spark"
      - "vendor"
    name: "*.php"
    not-name:
      - "*.blade.php"
      - "*.twig.php"
      - "helper.php"
